### ISSUE TITLE
Fail sending message to artemis-2.6.3

### ISSUE THREAD

**Issue by rbomfim** [Havret/dotnet-activemq-artemis-client#259]
## Describe the bug 
When sending a message to the broker I get the following error:

```
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (org.apache.qpid.proton.amqp.UnsignedByte cannot be cast to java.lang.Byte)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Sandbox.Program.Main(String[] args)

  This exception was originally thrown at this call stack:
    [External Code]
    ActiveMQ.Artemis.Client.ProducerBase.SendInternalAsync(string, ActiveMQ.Artemis.Client.RoutingType?, ActiveMQ.Artemis.Client.Message, ActiveMQ.Artemis.Client.Transactions.Transaction, System.Threading.CancellationToken) in ProducerBase.cs
    [External Code]
    ActiveMQ.Artemis.Client.AutoRecovering.AutoRecoveringProducer.SendAsync(ActiveMQ.Artemis.Client.Message, ActiveMQ.Artemis.Client.Transactions.Transaction, System.Threading.CancellationToken) in AutoRecoveringProducer.cs
    [External Code]
    Sandboxed.Program.Enviar() in Program.cs

Inner Exception 1:
MessageSendException: org.apache.qpid.proton.amqp.UnsignedByte cannot be cast to java.lang.Byte
```

## Expected behavior
The message should be sent.

## Environment:

- OS: [OS name and version, e.g. Ubuntu 20.04]
- Version: 2.1.0
- Broker: ActiveMQ Artemis 2.6.3

**Comment by Havret** [comment]
Your fix is released in version [2.1.1](https://www.nuget.org/packages/ArtemisNetClient/2.1.1). If you're using [ActiveMQ Artemis .NET Client extensions](https://github.com/Havret/activemq-artemis-extensions) I can bump up the version there as well.

**Comment by rbomfim** [comment]
Yes, I'm using [ActiveMQ Artemis .NET Client extensions](https://github.com/Havret/activemq-artemis-extensions) too.

**Comment by Havret** [comment]
ActiveMQ Artemis .NET Client extensions updated as well.
